variables:
    GIT_STRATEGY: clone

stages:
  - check raw html
  - build pdf
  - build html
  - deploy

fail_if_contain_raw_html:
  stage: check raw html
  image: sjtuhpc/texlive-sphinx:focal
  tags:
    - docker
  before_script:
    - apt-get update -y
    - apt-get install -y ack-grep
  script:
    - ack '.*raw.*html' docs && false || true

build_briefmanual_pdf:
  stage: build pdf
  image: sjtuhpc/texlive-sphinx:focal
  tags:
    - docker
  before_script:
    - mkdir -p .build_cache
    - pip3 install --cache-dir=.build_cache -r requirements.txt
  script:
    - make -C tex all
  artifacts:
    paths:
      - tex/main.pdf
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .build_cache


build_latex_pdf:
  stage: build pdf
  image: sjtuhpc/texlive-sphinx:focal
  tags:
    - docker
  before_script:
    - mkdir -p .build_cache
    - pip3 install --cache-dir=.build_cache -r requirements.txt
  script:
    - make -C docs clean latexpdf
    - pdftk A=docs/img/cover.pdf B=docs/_build/latex/sphinx.pdf cat A1 B2-end output docs/_build/latex/merge.pdf
    - gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH -sOutputFile=docs/_build/latex/pi_small.pdf docs/_build/latex/merge.pdf
    - mv docs/_build/latex/pi_small.pdf  docs/_build/latex/pi.pdf
  artifacts:
    paths:
      - docs/_build/latex/pi.pdf
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .build_cache

build_html_pages:
  stage: build html
  image: sjtuhpc/texlive-sphinx:focal
  tags:
    - docker
  needs:
    - job: build_latex_pdf
      artifacts: true
    - job: build_briefmanual_pdf
      artifacts: true
  before_script:
    - mkdir -p .build_cache
    - pip3 install --cache-dir=.build_cache -r requirements.txt
    - pip3 install sphinx_immaterial
  script:
    - mkdir docs/_static || true
    - cp docs/_build/latex/pi.pdf docs/_static/hpcmanual.pdf
    - cp tex/main.pdf docs/_static/hpcbriefmanual.pdf
    - make -C docs clean html
  artifacts:
    paths:
      - docs/_build/html
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .build_cache
     
deploy_html_to_hpc:
  stage: deploy
  tags:
    - shell.web.hpc.sjtu.edu.cn
  only:
    - master
  script:
    - rsync -avr --progress --delete docs/_build/html/ /var/lib/www/docs.hpc.sjtu.edu.cn/
