variables:
    GIT_STRATEGY: clone

stages:
  - check raw html
  - build pdf
  - build html
  - deploy

pre_check:
  stage: check raw html
  tags:
    - sphinx
  script:
    - ack '.*raw.*html' docs && false || true
    - rm -rf /tmp/doc_cache
    - mkdir -p /tmp/doc_cache

build_briefmanual_pdf:
  stage: build pdf
  tags:
    - sphinx
  script:
    - source /opt/sphinx/bin/activate
    - make -C tex main.pdf
  artifacts:
    paths:
      - tex/main.pdf
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - /tmp/doc_cache

build_cover:
  stage: build pdf
  tags:
    - sphinx
  script:
    - source /opt/sphinx/bin/activate
    - make -C tex cover.pdf
  artifacts:
    paths:
      - tex/cover.pdf
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - /tmp/doc_cache

build_latex_pdf:
  stage: build pdf
  tags:
    - sphinx
  needs:
    - job: build_cover
      artifacts: true
  script:
    - source /opt/sphinx/bin/activate
    - make -C docs clean latexpdf
    - pdftk A=tex/cover.pdf B=docs/_build/latex/sphinx.pdf cat A1 B2-end output docs/_build/latex/merge.pdf
    - gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH -sOutputFile=docs/_build/latex/pi_small.pdf docs/_build/latex/merge.pdf
    - mv docs/_build/latex/pi_small.pdf  docs/_build/latex/pi.pdf
  artifacts:
    paths:
      - docs/_build/latex/pi.pdf
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - /tmp/doc_cache

build_html_pages:
  stage: build html
  tags:
    - sphinx
  needs:
    - job: build_latex_pdf
      artifacts: true
    - job: build_briefmanual_pdf
      artifacts: true
  script:
    - source /opt/sphinx/bin/activate
    - mkdir docs/_static || true
    - cp docs/_build/latex/pi.pdf docs/_static/hpcmanual.pdf
    - cp tex/main.pdf docs/_static/hpcbriefmanual.pdf
    - make -C docs clean html
  artifacts:
    paths:
      - docs/_build/html
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - /tmp/doc_cache
     
deploy_html_to_hpc:
  stage: deploy
  tags:
    - shell.web.hpc.sjtu.edu.cn
  only:
    - master
  script:
    - rsync -avr --progress --delete docs/_build/html/ /var/lib/www/docs.hpc.sjtu.edu.cn/
