variables:
    GIT_STRATEGY: clone

stages:
  - check raw html
  - build pdf
  - build html
  - deploy

fail_if_contain_raw_html:
  stage: check raw html
  image: sjtuhpc/texlive-sphinx
  tags:
    - docker
  before_script:
    - apt-get update -y
    - apt-get install -y ack-grep
  script:
    - ack '.*raw.*html' docs
    - if [ $? -e 0 ]; then false; fi;

build_latex_pdf:
  stage: build pdf
  image: sjtuhpc/texlive-sphinx
  tags:
    - docker
  before_script:
    - mkdir -p .build_cache
    - pip3 install --upgrade --cache-dir=.build_cache -r requirements.txt
  script:
    - make -C docs clean latexpdf
    - gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH -sOutputFile=docs/_build/latex/pi_small.pdf docs/_build/latex/pi.pdf
    - mv docs/_build/latex/pi_small.pdf  docs/_build/latex/pi.pdf
  artifacts:
    paths:
      - docs/_build/latex/pi.pdf
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .build_cache

build_html_pages:
  stage: build html
  image: sjtuhpc/texlive-sphinx
  tags:
    - docker
  needs:
    - job: build_latex_pdf
      artifacts: true
  before_script:
    - mkdir -p .build_cache
    - pip3 install --upgrade --cache-dir=.build_cache -r requirements.txt
  script:
    - mkdir docs/_static || true
    - cp docs/_build/latex/pi.pdf docs/_static/hpcmanual.pdf
    - make -C docs clean html
  artifacts:
    paths:
      - docs/_build/html
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .build_cache
     
deploy_html_and_pdf_to_nginx_directory:
  stage: deploy
  tags:
    - shell.web.hpc.sjtu.edu.cn
  only:
    - master
    - merge_request
    - sphinx
  script:
    - rsync -avr --progress --delete docs/_build/html/ /var/lib/www/docs.jianwen.me/
