variables:
    GIT_STRATEGY: clone

stages:
  - build
  - deploy

build html pages:
  stage: build
  image: python:3.7
  tags:
    - docker.web.hpc.sjtu.edu.cn
  before_script:
    - mkdir -p .build_cache
    - pip install --upgrade --cache-dir=.build_cache -r requirements.txt
  script:
    - make -C docs html
  artifacts:
    paths:
      - docs/_build/html
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .build_cache

deploy html to nginx directory:
  stage: deploy
  tags:
    - shell.proxy.pi.sjtu.edu.cn
  only:
    - master
    - merge_request
    - sphinx
  script:
    - rsync -avr --progress --delete docs/_build/html/ /var/lib/www/hpc.pi.sjtu.edu.cn/
